[features]
seeds = false

[programs.localnet]
create_system_account = "5ELLotsEovMZFVev4rLDtDuxAqXa4LyCfWbXvkHLxEDB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"  # Change to localnet
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"